### ISSUE TITLE
Support installation on Mac OS

### ISSUE THREAD

**Issue by jkopczyn** [df7cb/sdate#1]
Not all people who need to know the day of September use Linux

**Comment by df7cb** [comment]
I need to clean up the automake/autoconf-iguration of the package in general. Or rebase the patch on top of current fakeroot...

**Comment by df7cb** [comment]
I'm guessing running `./bootstrap && make` should Just Work.

**Comment by georgemoodier** [comment]
sadly sdate only outputs `sdate: preload library not found in /usr/local/lib:/usr/local/lib64/libsdate, aborting.` when using this method, here’s the entire process:

[![asciicast](https://asciinema.org/a/b17vyJZZSBVfRf97dMDIEciJG.svg)](https://asciinema.org/a/b17vyJZZSBVfRf97dMDIEciJG)

(macOS Sonoma Version 14.2.1 (23C71))

**Comment by weakish** [comment]
> sdate: preload library not found in /usr/local/lib:/usr/local/lib64/libsdate

The `sdate` script will try to find `libsdate.so.0`, but under macOS it's `libsdate.dylib` instead.

However, on my machine (macOS 14.2.1 with SIP enabled),
`sdate -l .libs/libsdate.dylib` is the same as `date`.
