### ISSUE TITLE
Does sdate have a birth day? How old is it?

### ISSUE THREAD

**Issue by ghost** [df7cb/sdate#10]
Is it known when sdate was actually created? Given it's origins, I thought the date sdate was created would have been a relevant enough detail that'd it'd be part of the back story. Is there a specific date or a range of time that'd confirm how old it is?

**Comment by df7cb** [comment]
Do you mean http://www.catb.org/~esr/jargon/html/S/September-that-never-ended.html or the `sdate` program?

**Comment by georgemoodier** [comment]
i would actually like to know about the history of the program, Eternal September's (the event that is) origins and history seem comparatively more documented.

**Comment by df7cb** [comment]
The initial git commit is from Sat Sep 4064 15:28:11 1993 (converted from svn).
