### ISSUE TITLE
Running bootstrap complains about missing files.

### ISSUE THREAD

**Issue by LittleTimmy63** [df7cb/sdate#5]
Used release 0.7.
The output is the following {
+ aclocal
+ autoheader
+ libtoolize
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
+ automake
configure.ac:10: error: required file './compile' not found
configure.ac:10:   'automake --add-missing' can install 'compile'
configure.ac:5: error: required file './install-sh' not found
configure.ac:5:   'automake --add-missing' can install 'install-sh'
configure.ac:5: error: required file './missing' not found
configure.ac:5:   'automake --add-missing' can install 'missing'
Makefile.am: error: required file './depcomp' not found
Makefile.am:   'automake --add-missing' can install 'depcomp'
}
Judging by the period this means that certain files expected to be in the directory are missing.
My distro is Fedora 33, if that helps.

**Comment by cheznewa** [comment]
Type :::::: `autoreconf -i` Then `./configure` And `make`
The LD_Preload is Located ::::::::: **.libs/libsdate.so**
The Test ::::::::::: `LD_PRELOAD=./.libs/libsdate.so ./localtime`
